[project]
name = "CRISPRito"
version = "0.0.2"
description = "Comprehensive nomination of CRISPR sites from cutting and editing data"
readme = "README.md"
requires-python = ">=3.7"
#license = {file = "LICENSE"}

authors = [
	{name = "Alexander McFarland"}
]
maintainers = [
	{name = "Alexander McFarland"}
]

classifiers = [
	"Development Status :: 5 - Production/Stable",
	"License :: OSI Approved :: MIT License",
	"Programming Language :: Python :: 3.10",
	"Programming Language :: Python :: 3.11",
]

dependencies = [
	"biopython",
	"numpy",
	"pandas"
]

[project.optional-dependencies]
dev = ["black"]
test = ["pytest", "pytest-cov"]

[project.urls]
"Homepage" = "https://github.com/agmcfarland/CRISPRito/"
"Bug Reports" = "https://github.com/agmcfarland/CRISPRito/issues"
"Source" = "https://github.com/agmcfarland/CRISPRito/"

[project.scripts]
setup_run = "CRISPRito.SetupRun:main"
process_group = "CRISPRito.ProcessGroup:main"
CRISPRito_cut = " CRISPRito.CRISPRito:main"

# [tool.setuptools]
# packages = ["CRISPRito"]
# package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"
